services:
  dev_db:
    image: mysql:8
    container_name: murmur_db
    environment:
      MYSQL_ROOT_PASSWORD: "abdurrahman$123"
      MYSQL_DATABASE: murmur
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
